### ISSUE TITLE
Day one code review

### ISSUE THREAD

**Issue by alexander16108** [Munsa1/Awesome-Books#2]
## Congratulation to you two 👏🏾 

Your project looks well thought out and organized but the are few more steps to take before it called the perfect code

- your css file could be in the same subfolder to make your repo look clean and more organised 

- your js file on line 50 could be changed because it throws Errors.

other than that its good to go 👍🏾 

cheer and happy coding 
Alexander

**Comment by sheylaPozo** [comment]
thanks
